// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using DtPipeline.DbModel;
using DtPipeline.Bridge;

namespace DtPipeline.DbData
{
    public partial class DataPipelineContext : DbContext
    {
        public DataPipelineContext()
        {
        }

        public DataPipelineContext(DbContextOptions<DataPipelineContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AccountDatum> AccountData { get; set; }
        public virtual DbSet<CustomerDatum> CustomerData { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnModelCreatingPartial(modelBuilder);
        }

        #region test

        protected override void OnConfiguring(DbContextOptionsBuilder builder)
        {
            builder.UseSqlServer(Setting.returnSQLConnectionString());
        }

        #endregion

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}