// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DtPipeline.DbModel
{
    public partial class CustomerDatum
    {
        [Key]
        public int Id { get; set; }
        [Column("ChargingPartyID")]
        public int? ChargingPartyId { get; set; }
        public int? SortCode { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string AccountNumber { get; set; }
        [Column("TINorGHCard")]
        [StringLength(50)]
        [Unicode(false)]
        public string TinorGhcard { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string PhoneNumber { get; set; }
        [Column("ShortID")]
        [StringLength(50)]
        [Unicode(false)]
        public string ShortId { get; set; }
        [Column("Unique_Id_Name")]
        [StringLength(50)]
        [Unicode(false)]
        public string UniqueIdName { get; set; }
    }
}